"""checked_in,checked_in_date,checked_out,checked_out_date in bookings table

Revision ID: 175c6fbc28eb
Revises: 3e4ededacdf7
Create Date: 2025-11-15 14:03:51.593584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175c6fbc28eb'
down_revision: Union[str, Sequence[str], None] = '3e4ededacdf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('checked_in', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('checked_in_date', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('checked_out', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('checked_out_date', sa.DateTime(), nullable=True))
    
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('bookings', 'checked_out_date')
    op.drop_column('bookings', 'checked_out')
    op.drop_column('bookings', 'checked_in_date')
    op.drop_column('bookings', 'checked_in')
    # ### end Alembic commands ###
