"""add pool_used_by, pool_used_start_date and pool_used_time atrributes in booking table

Revision ID: 25747d7df28a
Revises: 175c6fbc28eb
Create Date: 2025-11-16 22:00:03.082033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25747d7df28a'
down_revision: Union[str, Sequence[str], None] = '175c6fbc28eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('pool_used_by', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('pool_used__start_date', sa.DateTime(), nullable=True))
   
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'pool_used__start_date')
    op.drop_column('bookings', 'pool_used_by')
    
    # ### end Alembic commands ###
