"""price attribute in single,deluxe,cottage

Revision ID: 25b049f4e220
Revises: 9f1e63d25887
Create Date: 2025-11-12 19:37:07.267607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b049f4e220'
down_revision: Union[str, Sequence[str], None] = '9f1e63d25887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cottageroom', sa.Column('price', sa.Float(), default=6000.0))
    op.add_column('deluxeroom', sa.Column('price', sa.Float(), default=3000.0))
    op.add_column('singleroom', sa.Column('price', sa.Float(), default=2000.0))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('singleroom', 'price')
    op.drop_column('deluxeroom', 'price')
    op.drop_column('cottageroom', 'price')
    pass
    # ### end Alembic commands ###
