"""room_no coloumn in booking table 

Revision ID: 3e4ededacdf7
Revises: 7d7752167cdb
Create Date: 2025-11-14 19:57:35.756923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4ededacdf7'
down_revision: Union[str, Sequence[str], None] = '7d7752167cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('room_no', sa.Integer(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'room_no')
    # ### end Alembic commands ###
