"""feedback attribute in Booking Table

Revision ID: 453996f4fe22
Revises: d9e2dee066bb
Create Date: 2025-11-18 18:43:31.548434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453996f4fe22'
down_revision: Union[str, Sequence[str], None] = 'd9e2dee066bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('feedback', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('bookings', 'feedback')
    # ### end Alembic commands ###
