"""STATUS attribute in booking table

Revision ID: 7d7752167cdb
Revises: 25b049f4e220
Create Date: 2025-11-14 15:36:19.980891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7752167cdb'
down_revision: Union[str, Sequence[str], None] = '25b049f4e220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
   
    op.add_column('bookings', sa.Column('STATUS', sa.String(), nullable=False, server_default="pending"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'STATUS')
    # ### end Alembic commands ###
