"""occupied attribute in single,deluxe and cottage tables

Revision ID: 9f1e63d25887
Revises: 
Create Date: 2025-11-12 12:01:23.961742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1e63d25887'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cottageroom', sa.Column('occupied', sa.Boolean(),nullable=False, server_default=sa.text('false')))
    op.add_column('deluxeroom', sa.Column('occupied', sa.Boolean(),nullable=False, server_default=sa.text('false')))
    op.add_column('singleroom', sa.Column('occupied', sa.Boolean(),nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('singleroom', 'occupied')
    op.drop_column('deluxeroom', 'occupied')
    op.drop_column('cottageroom', 'occupied')
    # ### end Alembic commands ###
