"""transaction id in Booking table

Revision ID: d1e190681909
Revises: 453996f4fe22
Create Date: 2025-11-21 12:49:43.276618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e190681909'
down_revision: Union[str, Sequence[str], None] = '453996f4fe22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('transaction_id', sa.Integer(), autoincrement=True, unique=True, nullable=False))
    op.add_column('bookings', sa.Column('Received_amount', sa.Float(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_column('bookings', 'Received_amount')
    op.drop_column('bookings', 'transaction_id')
    # ### end Alembic commands ###
