"""add total_amount,advance_payment,payment_status attributes in Booking Table

Revision ID: d9e2dee066bb
Revises: 25747d7df28a
Create Date: 2025-11-17 19:35:51.000221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e2dee066bb'
down_revision: Union[str, Sequence[str], None] = '25747d7df28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('total_amount', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('advance_payment', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('paid_amount', sa.Float(), nullable=True, default=0.0))
    op.add_column('bookings', sa.Column('due_amount', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('payment_status', sa.String(), nullable=True, default="PENDING"))
    op.add_column('bookings', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('razorpay_payment_id', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('razorpay_signature', sa.String(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_column('bookings', 'payment_status')
    op.drop_column('bookings', 'due_amount')
    op.drop_column('bookings', 'paid_amount')
    op.drop_column('bookings', 'razorpay_signature')
    op.drop_column('bookings', 'razorpay_payment_id')
    op.drop_column('bookings', 'razorpay_order_id')
    op.drop_column('bookings', 'advance_payment')
    op.drop_column('bookings', 'total_amount')
    # ### end Alembic commands ###
